### ISSUE TITLE
Error: ‘optixModuleCreateFromPTX’ was not declared in this scope; did you mean ‘optixModuleCreate’

### ISSUE THREAD

**Issue by jspanchu** [NVIDIA/VisRTX#48]
The README.md states Optix 7.4+ will work when instead, the VisRTX device fails to compile
```
VisRTX/devices/rtx/VisRTXDevice.cpp:600:17: error: ‘optixModuleCreateFromPTX’ was
not declared in this scope; did you mean ‘optixModuleCreate’?
```

It appears that `optixModuleCreateFromPTX` was renamed to `optixModuleCreate` in [Optix 7.7](https://developer.download.nvidia.com/designworks/optix/secure/7.7/OptiX_Release_Notes_7.7_01.pdf?ZC-MMuBHhd4nvE3e2XysLGmpIyKtWxFVLW_Ey-AqvbqxvAo1A_SdE4IRO65mSO3dARz9A2_hTsz66WUqjoWXBbIJajLF3Eq6mxlZwAvDUHekOqVIVfzSGxQfaPLG-9DT6ChHqefA3MJQuo3NgJk5rY-EbhWauahxTCY=&t=eyJscyI6ImdzZW8iLCJsc2QiOiJodHRwczovL3d3dy5nb29nbGUuY29tLyJ9)

**Comment by jeffamstutz** [comment]
Thanks for this, I'll work on getting in a fix ASAP -- in the mean time, using an older version of OptiX will suffice (driver can stay the same), if that's not too much of a hassle for you.

**Comment by jeffamstutz** [comment]
Just pushed a fix to `next_release` that will build with both versions 7.7 and older. Let us know if you have any other issues!

**Comment by jspanchu** [comment]
Got the VisRTX demo viewer working. However I've noticed that the `viewer` seemed to freeze during startup. When I interrupted execution in a debugger, it appeared to take very long amount of time just inside `init_module(state.rendererModules.scivis, SciVis::ptx());`. After a couple of trials, it works now. Was it trying to compile and cache something?

**Comment by jeffamstutz** [comment]
Yes, the initial compile of OptiX programs takes a very long time. Messages indicating this get sent through the standard ANARI message callbacks, but the viewer hides everything that is less than a warning unless you pass `-v` on the command line. After the OptiX shader cache gets populated (i.e. everything compiles at least once), then startups should be very fast.

Glad to see it working for you!
